# Generated by Django 2.1.3 on 2018-11-03 00:31

import SpellChecker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpellChecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[SpellChecker.validators.validate_file_contents]),
        ),
    ]
